# Permalinks
permalink:        pretty

title:            Janmelin's Blog
description:      'Word from Nobady.'

baseurl:          /Blog

paginate:         8

version:          1.0.0

githubrepo:             https://github.com/Janmelin/Blog