# Permalinks
permalink:        pretty

title:            Joe Tang's Blog
description:      'Murmur from Joe.'

baseurl:          /blog

paginate:         8

version:          1.0.1

githubrepo:       https://github.com/Janmelin/Blog