# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'

baseurl:          https://janmelin.github.io/Blog/

paginate:         8

version:          1.0.0

github:
  repo:           https://github.com/janmelin/Blog
