# Permalinks
permalink:        pretty

title:            Words from NOBODY
description:      'Nothing.'

baseurl:          /Blog

paginate:         8

version:          1.0.0

github:
repo:             https://github.com/Janmelin/Blog